# For more info on HTTP files go to https://aka.ms/vs/httpfile
@hostname=localhost
@port=7093
@host={{hostname}}:{{port}}


POST https://localhost:7093/api/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=test%40test.com&password=P%40ssw0rd123_&grant_type=password